### ISSUE TITLE
Teleporting over large distance causes server to crash

### ISSUE THREAD

**Issue by DarkEyeDragon** [DarkEyeDragon/RandomTeleport#190]
**Describe the bug**
When teleporting to a distant location there is a chance your server will throw exceptions and eventually crash

**To Reproduce**
1. Use the worldborder as radius
2. Set worldborder to big value like 3000000
3. /rtp

**Expected behavior**
For player to be teleported without crashing the server

**Screenshots**

**Minecraft Version**
1.18.x

**Plugin version**
Pretty sure this affects all versions

**Additional context**
Related to https://github.com/PaperMC/Paper/issues/7006

Solution:
Don't set  your radius too big. Anything below 50.000 should be fine.
or
you can set `use-async-chunk-teleport` to false (default) in the config in the `teleport` section from version 2.1.0.136 
(https://ci.darkeyedragon.me/job/Random%20Teleport)
example:
```yaml
teleport:
  ...
  #Minecraft 1.18 seems to have issues with large (chunk) locations causing it to crash.
  #Setting this to false will teleport on the main thread preventing this issue but will block the main thread
  #For more info check: https://github.com/DarkEyeDragon/RandomTeleport/issues/190
  use-async-chunk-teleport: false
```
